services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "MySecretPassword1234"
      PGDATA: /data/postgres
      POSTGRES_DB: "cars"
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "MySecretPassword1234"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./config/pg-servers.json:/pgadmin4/servers.json # preconfigured servers/connections
      - ./config/pg-pass:/pgpass # passwords for the connections in this file

    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: